### ISSUE TITLE
Remove home controller

### ISSUE THREAD

**Issue by MarkDBlackwell** [akshatpradhan/spoutlets#36]
We don't use the home controller anymore. And it has a broken test, which breaks our test suite.

**Comment by akshatpradhan** [comment]
I question if we should do this right now. I ask because the current landing page isn't exactly the best. And perhaps we need the Home Controller in the future. 

Also, regarding testing, I'm going to hold off on it now. After reading @priyaaank pull request and him saying that, "there isn't really anything to test right now, because its all basic functionality", I'm starting to realize that its important to actually build the front end experience first, and then write out the test cases. 

I know this is the anti-"test first", but because this is an MVP, and we don't know how people will even behave on the site, it might not make sense writing a big beautiful test suite, only so that people don't even use us.
