### ISSUE TITLE
Log an Entry When Not Logged In - Bug

### ISSUE THREAD

**Issue by billiedemott** [akshatpradhan/spoutlets#55]
Given I'm on http://www.spoutlets.com/entries/new, and not logged in
When I click "Log it"
Then I should see a prompt that indicates I should "login/register" rather then getting the message, "The page you were looking for doesn't exist.":

Instead of this
![Screen Shot 2013-03-27 at 8 21 59 PM](https://f.cloud.github.com/assets/331004/311367/8c51786e-973d-11e2-9b46-b5bb8e01cc1e.png)

It should look like this
![Screen Shot 2013-03-08 at 9 30 43 AM](https://f.cloud.github.com/assets/1459738/237244/6fb3414e-880e-11e2-9eb2-afe8f0232896.png)

**Comment by MarkDBlackwell** [comment]
Perhaps the code after login should remember to go back automatically to the entries/new page.

Then hopefully the browser will have the form still filled in and ready for another click of "Log it".

**Comment by MarkDBlackwell** [comment]
It's possible for people to navigate in many ways to the URL, http://www.spoutlets.com/entries/new:
- By clicking the Spoutlets button, "log an entry";
- By opening a browser bookmark (for that URL); or
- By some other method.

There's another way in which we could solve the basic issue here. If the user is not logged in, then navigating to that URL could cause a redirection instead to the home page. If we handled things that way, then a prompt would inform the user they must click "login/register" first. In other words, this redirection would happen before the user could type the entry in the first place.

The important thing is that this depends on marketing. Which way is marketing's preference here? We can allow an entry to be typed before login, or we can require login before typing an entry.  Any preference?

Perhaps it's already been decided, and I've missed that. @akshatpradhan, which way should the solution go?

**Comment by akshatpradhan** [comment]
Actually, for now, 

Given I'm not logged in
When I click `log an entry`
Then I should see this
![Screen Shot 2013-03-08 at 9 30 43 AM](https://f.cloud.github.com/assets/1459738/237244/6fb3414e-880e-11e2-9eb2-afe8f0232896.png)

Given I'm not `logged in`
When I click `log an entry`
and When I fill out an `entry`
and When I click `Log it!`
Then I should be redirected back to `/entries/new`

(Basically they're haven't gone anywhere)

**Comment by MarkDBlackwell** [comment]
@akshatpradhan, you seem to be telling me that it's fine for logged out users to indeed see the `/entries/new` page.

But after typing in their entry, without being able to save it at this point, when they click the Register or Login link, they might lose their entry. That's the problem I'm bringing up. And that whole problem is prevented by keeping logged out users from seeing that page in the first place.

My partner says, "'Why would you ever want to have an entry form that you can't save?"

My impression is, I can't think of any websites that let logged out users enter things, only to tell them they have to log in before they can save their "work"!

I'm also confused because you say, "for now". Do you say "for now" because you think stopping them is difficult to do? I am sure that:
- It's extremely easy for us to prevent logged out users ever seeing the `/entries/new` page.

Or do you mean for marketing purposes it's better to show `/entries/new` even to logged out users? That would be fine. Please advise.

In order to entice new users to register, it might be easier to show them an entry form that's not "live", such as an attractive image of the entry form, on the home page or elsewhere.

**Comment by akshatpradhan** [comment]
@MarkDBlackwell I recognize all of this, and I'm glad you're aware of this too. Its actually a bad experience when you fill out the form, then register, and then have to fill it out again. But its also a bad marketing experience to force someone to sign up, just to see how the form for Logging an Entry looks. Either way, both experiences are bad. The problem that needs to be figured out first is how the modal will work when someone clicks login/register. We still need to bring therapists on board. I'll explain the problem over a skype session, but we do need to keep all of what you said in mind and address it real quickly.

**Comment by MarkDBlackwell** [comment]
@akshatpradhan, thanks for the clarifying answer!

I'll start straightaway remolding this to the way you would like. :)

**Comment by akshatpradhan** [comment]
Fixed https://github.com/akshatpradhan/spoutlets/pull/116
