### ISSUE TITLE
Only Show Progress Bars for Rated Moods; Remove Empty Progress Bars

### ISSUE THREAD

**Issue by billiedemott** [akshatpradhan/spoutlets#65]
Given I'm on http://www.spoutlets.com/entries (my community) or http://www.spoutlets.com/users/512e9ae890462866f3000001 (my journal),
When I see an entry that doesn't have a rating for happiness, anxiety or irritation,
Then I shouldn't see an empty progress bar for that mood, but instead just see progress bars for what has been rated. 

![Screen Shot 2013-03-17 at 3 21 11 PM](https://f.cloud.github.com/assets/1459738/268504/61ef0364-8f38-11e2-8875-29545003d66b.png)

In this example, only a progress bar for happiness would appear. No progress bars for anxiety & irritation would appear as they haven't been rated.

**Comment by MarkDBlackwell** [comment]
I observe the anxiety and irritation progress bars in your example are almost invisible, with no blue color there. However, I think I understand you to mean the headings should not appear either.

When you say unrated, are you talking about the value 0? (As far as the program is concerned, this is the way the default is stored in the database.) Of course, in a sense, 0 is the value obtained by the software if a user doesn't move the blue dot away from its initial position. I guess I misunderstood before what the value 0 meant. However, I believe that marketing's input is all-important here. :)

Previously, I was assuming a user might want to enter mood level 0. Would that be a valid mood level? Or should we somewhere explain this value is for unrated moods only? (Or perhaps we should leave it implicit.)

If a user doesn't detect any of a certain mood, would the user want to use the number 0 for that situation? As in, the level is zero? Yet when a user is out of touch temporarily with their emotions, I guess they would want to say they don't feel anything then too, and would choose the lowest value. Perhaps they then wouldn't prefer to leave it unrated—or would they?

What if a user edits their entry, even a minute later, to correct their mood level down from 1 to 0, because they decided they hadn't entered it correctly before? and now they remember they actually felt that mood at level 0? What should we do? What should it mean? I guess we should make explicit what 0 means ahead of time: that either it means unrated, or the lowest rated mood value. Could we make it mean both? Somehow I don't think so.

I think allowing unrated moods could be good functionality, possibly. On the other hand, leaving moods unrated could be less fun, less liked by users. Would more users prefer being asked for (and being required to enter) these three mood levels for every entry, as a fun, easy, information-gathering thing? Presumably, this information is easily available to any user. And we've made it extremely easy and fun to enter their mood levels by these big blue dots.

Currently the spline chart (worked up, but not yet in the master branch) thinks of the 0's as valid ratings. Maybe the HighChart gem could be informed that 0 means the data is missing. If this is important to know, I could find out.

In the end, whether to include unrated moods (as functionality) is for marketing to decide, IMO. @akshatpradhan, was this decision already made?

**Comment by MarkDBlackwell** [comment]
If we go with the idea that mood level 0 means it is unrated...

Should the remaining mood rating bars be placed in their same positions? Thus for instance if anxiety (or irritation) is the only rated mood, it would not be positioned at the left. Instead, it would be positioned where it usually is, thus keeping the same visual interface.

Or, should the remaining, rated moods be pulled to the left edge?
